-- SQLite
INSERT INTO MOVIES VALUES ('SHAH RUKH KHAN', 'DEEPIKA PADUKONE', 'HAIDER ALI', 2000);
INSERT INTO MOVIES VALUES ('HRITIK ROSHAN', 'PRIYNAKA CHOPRA', 'AANAND L RAI', 2001);
INSERT INTO MOVIES VALUES ('SHAH RUKH KHAN', 'PRIYNAKA CHOPRA', 'RAKESH ROSHAN', 2013);
INSERT INTO MOVIES VALUES ('AKSHAY KUMAR', 'KATRINA KAIF', 'RAJKUMAR', 2009);
INSERT INTO MOVIES VALUES ('SHAH RUKH KHAN', 'DEEPIKA PADUKONE', 'RAJKUMAR', 2014);
INSERT INTO MOVIES VALUES ('RANBIR KAPOOR', 'KAREENA KAPOOR', 'MOHIT SURI', 2016);

